[book]
authors = ["Henk Oordt", "Dion Dokter"]
language = "en"
multilingual = false
src = "material"
title = "Workshop embedded Rust"

[output.html]
additional-css = ["material/assets/style/main.css"]
additional-js = ["material/assets/js/main.js"]